CREATE
  TABLE SHOUKAISEKI_INSERT_KKS
  (
    "ID"          NUMBER NOT NULL ENABLE,
    "LOCATION"    VARCHAR2(30 CHAR),
    "DESCRIPTION" VARCHAR2(200 CHAR),
    "PARENT"      VARCHAR2(30 CHAR),
    "CFL"         NUMBER,
    "CFD"         NUMBER,
    "ALLCFL"      NUMBER,
    "ALLCFD"      NUMBER,
    "SETUMEINUM"  NUMBER,
    "SETUMEI"     VARCHAR2(100 CHAR),
    "SETUMEI2"    VARCHAR2(100 CHAR),
    "COLUMN1"     VARCHAR2(300 BYTE),
    "COLUMN2"     VARCHAR2(300 BYTE),
    "COLUMN3"     VARCHAR2(300 BYTE),
    "COLUMN4"     VARCHAR2(300 BYTE),
    "COLUMN5"     VARCHAR2(300 BYTE),
    "COLUMN6"     VARCHAR2(300 BYTE),
    "COLUMN7"     VARCHAR2(300 BYTE),
    "COLUMN8"     VARCHAR2(300 BYTE),
    "COLUMN9"     VARCHAR2(300 BYTE),
    "COLUMN10"    VARCHAR2(300 BYTE),
    "COLUMN11"    VARCHAR2(300 BYTE),
    "COLUMN12"    VARCHAR2(300 BYTE),
    "COLUMN13"    VARCHAR2(300 BYTE),
    "COLUMN14"    VARCHAR2(300 BYTE),
    "COLUMN15"    VARCHAR2(300 BYTE),
    "COLUMN16"    VARCHAR2(300 BYTE),
    "COLUMN17"    VARCHAR2(300 BYTE),
    "COLUMN18"    VARCHAR2(300 BYTE),
    "COLUMN19"    VARCHAR2(300 BYTE),
    "COLUMN20"    VARCHAR2(300 BYTE),
    "COLUMN21"    VARCHAR2(300 BYTE),
    "COLUMN22"    VARCHAR2(300 BYTE),
    "COLUMN23"    VARCHAR2(300 BYTE),
    "COLUMN24"    VARCHAR2(300 BYTE),
    "COLUMN25"    VARCHAR2(300 BYTE),
    "COLUMN26"    VARCHAR2(300 BYTE),
    "COLUMN27"    VARCHAR2(300 BYTE),
    "COLUMN28"    VARCHAR2(300 BYTE),
    "COLUMN29"    VARCHAR2(300 BYTE),
    "COLUMN30"    VARCHAR2(300 BYTE)
  );
--主键(包含唯一索引功能)
ALTER TABLE SHOUKAISEKI_INSERT_KKS
ADD CONSTRAINT SHOUKAISEKI_INSERT_KKS_PK PRIMARY KEY 
(
  ID 
)
ENABLE;
 
--建立索引,优化查询效率
CREATE INDEX SHOUKAISEKI_INSERT_KKS_INDEX1 ON SHOUKAISEKI_INSERT_KKS (LOCATION);

CREATE INDEX SHOUKAISEKI_INSERT_KKS_INDEX2 ON SHOUKAISEKI_INSERT_KKS (DESCRIPTION);

CREATE INDEX SHOUKAISEKI_INSERT_KKS_INDEX3 ON SHOUKAISEKI_INSERT_KKS (LOCATION, DESCRIPTION);

CREATE INDEX SHOUKAISEKI_INSERT_KKS_INDEX4 ON SHOUKAISEKI_INSERT_KKS (PARENT);


